typography_spectrum: 0.40441945591010153
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.8564219495747238
  lightness: 0.2700090720318258
  saturation: 0.41265360545367
  rhythmicContrast: 0.035384057089686394
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24283
analytics:
  google: null
  facebook: null
  twitter: null
name: stevegw-human-form
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    url: 'http://stevegw.today'
    type: external
  - name: Pastels
    url: 'http://thegrid.ai/sketchytime-pastels'
    type: external
  - name: Game Art
    url: 'http://thegrid.ai/sketchytime-game-art'
    type: external
  - name: About
    url: 'http://thegrid.ai/stevegw-about'
    type: external
favicon: null
title: Human Form
description: 'Most know and most critiqued '
purpose: []
